image: python:3.7-stretch

stages:
  - documentation
  - unit_tests


# install and activate the virtual env
before_script:
  - pip install --upgrade pip setuptools
  - pip install virtualenv
  - virtualenv -p `which python` .virtualenv/AffApy
  - source .virtualenv/AffApy/bin/activate

# template for the unit tests
.unittest:
  stage: unit_tests
  script:
    # install AffApy and coverage
    - pip install .
    - pip install coverage
    # run the unit tests and report the coverage
    - coverage run --source=AffApy,test -m unittest discover -v test
    - coverage html
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    when: always
    paths:
      - htmlcov
    expire_in: 1 week

job:test-python2.7:
  extends: .unittest
  image: python:2.7-stretch

job:test-python3.5:
  extends: .unittest
  image: python:3.5-stretch

job:test-python3.6:
  extends: .unittest
  image: python:3.6-stretch

job:test-python3.7:
  extends: .unittest
  image: python:3.7-buster

job:test-python3.8:
  extends: .unittest
  image: python:3.8-buster



# generate pdf documentation
job:PDF:
  stage: documentation
  allow_failure: true
  script:
    # install minimal LaTeX
    - apt-get update -qy
    - apt-get -y install texlive-latex-recommended latexmk texlive-fonts-recommended texlive-science texlive-formats-extra texlive-lang-french
    # generate the html and the pdf documentation
    - pip install .
    - cd doc/
    - make html
    - make latexpdf
    - cd ..
  artifacts:
    paths:
      - doc/build/latex/affapy.pdf
      - doc/build/html/*
