uml:
	pyreverse -o dot -p affapy -A -S -f OTHER ../../affapy

png:
	dot -Tpng classes_affapy.dot -o uml.png

pdf:
	dot -Tpdf classes_affapy.dot -o uml.pdf

clear:
	rm classes_affapy.dot packages_affapy.dot
